#!/bin/bash

## Description: Launch aider in the web container
## Usage: aider
## Example: "ddev aider"

sudo apt update
sudo apt install pipx
pipx ensurepath

pipx install aider-chat
~/.local/bin/aider --mini --openai-api-key $OPENAI_API_KEY
